services:
  edge-a:
    image: hivemq/hivemq-edge:2025.12
    container_name: edge-a
    depends_on:
      - edge-b
      - toxiproxy
    ports:
      - "1883:1883"
      - "8080:8080"
    volumes:
      - edge-a-data:/opt/hivemq/data
      - ./config/edge-a/conf/config.xml:/opt/hivemq/conf/config.xml:ro
      - ./config/edge-shared/logback.xml:/opt/hivemq/conf/logback.xml:ro

  edge-b:
    image: hivemq/hivemq-edge:2025.12
    container_name: edge-b
    ports:
      - "1884:1883"
      - "8081:8080"
    volumes:
      - edge-b-data:/opt/hivemq/data
      - ./config/edge-b/conf/config.xml:/opt/hivemq/conf/config.xml:ro
      - ./config/edge-shared/logback.xml:/opt/hivemq/conf/logback.xml:ro

  toxiproxy:
    image: ghcr.io/shopify/toxiproxy:2.12.0
    container_name: toxiproxy
    depends_on:
      - edge-b
    command:
      - -host=0.0.0.0
      - -config=/config/toxiproxy.json
    ports:
      - "8474:8474"
      - "8666:8666"
    volumes:
      - ./config/toxiproxy/toxiproxy.json:/config/toxiproxy.json:ro

volumes:
  edge-a-data:
  edge-b-data:
